Revert "fedora: moving to ganeric branding"
This reverts commit da0d8d3311441d1fb7a0ed639c34562a079ffb81.
Without fedora branding live media creation fails with
 OSError: nothing matching
/var/tmp/lorax.imgutils.x3lnikv1/usr/share/anaconda/boot/syslinux-splash.png
in /

So until we add oVirt artwork we need to use fedora logos.

Change-Id: I9cc9c5e94a2fab6096dcd4b0d09ee1321275f061
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>